#! /usr/bin/env bash

# Zips personal Notes folder for easy backup
#
# Depends on NOTES_PATH being set
# Usage: cd to desired backup location, run script

if [[ -d "$NOTES_PATH" ]]
then
    date=$(date +%Y%m%d)
    filename="NotesBackup${date}.zip" 
    currentdir=$(pwd)
    echo "Zipping $NOTES_PATH to $filename}"

    # change to the zipping dir to avoid saving all the directories in filepath
    (cd "$NOTES_PATH" && zip -re "${currentdir}/$filename" .)
    exit 0
else
    echo "Invalid path"
    exit 1
fi
