#! /usr/bin/env node
/**
Sorts monthly statements into folders
Usage: cd to dir with statments, run this script
*/

var fs = require('fs');

fs.readdir('./', (err, files) => {
    files.forEach(file => { // iterate through files
        if (file.substring(0, 8) === 'TekSavvy') {
            moveTo(file, 'internet')
        } else if (file.substring(0, 5) === 'TELUS') {
            moveTo(file, 'phone');
        } else if (file.substring(0, 2) === 'TD') {
            moveTo(file, 'bank_statements');
        } else if (file.substring(0, 12) === 'DigitalOcean') {
            moveTo(file, 'web_hosting');
        } else if (file.substring(0, 10) === 'eStatement') {
            moveTo(file, 'BMO_credit_card');
        } else if (file.substring(0, 4) === 'File') {
            moveTo(file, 'storage_unit');
        } else if (/\d+_\d+\.pdf/.test(file)) {
            moveTo(file, 'advertising');
        } else if (/\d+\.pdf/.test(file)) {
            moveTo(file, 'email');
        }
    });
})

function moveTo(file, dirName) {
	console.log(`Moving ${file} to ${dirName});
    if (!fs.existsSync(dirName)) {
        fs.mkdirSync(dirName);
    }

    fs.rename(file, dirName + '/' + file, function() {})
}
