#!/usr/bin/env node

const Task = require("./task");
const task = new Task();
console.log(`${(new Date()).toISOString()}: running notes cron`);

(async function () {
  try {
    await task.run();
  } catch(e) {
    console.error(e);
  }
})();
