#!/usr/bin/env node

const DailyDigest = require("./scripts/dailyDigest");
const Update = require("./scripts/update");
const dailyDigest = new DailyDigest();
const update = new Update();

console.log(`${new Date().toISOString()}: running notes cron`);

(async function () {
  try {
    await update.run();
    await dailyDigest.run();
  } catch (e) {
    console.error(e);
  }
})();
